//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnderssonLinkWCFCallingProject.OrderServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference.IOrderService")]
    public interface IOrderService {
        
        // CODEGEN: Parameter 'GetOrdersResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrders", ReplyAction="http://tempuri.org/IOrderService/GetOrdersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AnderssonLinkWCFCallingProject.OrderServiceReference.GetOrdersResponse GetOrders(AnderssonLinkWCFCallingProject.OrderServiceReference.GetOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/DeleteOrder", ReplyAction="http://tempuri.org/IOrderService/DeleteOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool DeleteOrder(int orderId);
        
        // CODEGEN: Parameter 'description' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/InsertOrder", ReplyAction="http://tempuri.org/IOrderService/InsertOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderResponse InsertOrder(AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderRequest request);
        
        // CODEGEN: Parameter 'message' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/InsertOrderByObject", ReplyAction="http://tempuri.org/IOrderService/InsertOrderByObjectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderByObjectResponse InsertOrderByObject(AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderByObjectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrders", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdersRequest {
        
        public GetOrdersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrdersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetOrdersResult;
        
        public GetOrdersResponse() {
        }
        
        public GetOrdersResponse(System.Data.DataSet GetOrdersResult) {
            this.GetOrdersResult = GetOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int articleNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime orderDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime deliveryDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int quantity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int piecePrice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int customerNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public int customerOrderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string info;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string currency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string recipient;
        
        public InsertOrderRequest() {
        }
        
        public InsertOrderRequest(int articleNo, string description, System.DateTime orderDate, System.DateTime deliveryDate, int quantity, int piecePrice, string customer, int customerNo, int customerOrderNo, string info, string currency, string recipient) {
            this.articleNo = articleNo;
            this.description = description;
            this.orderDate = orderDate;
            this.deliveryDate = deliveryDate;
            this.quantity = quantity;
            this.piecePrice = piecePrice;
            this.customer = customer;
            this.customerNo = customerNo;
            this.customerOrderNo = customerOrderNo;
            this.info = info;
            this.currency = currency;
            this.recipient = recipient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertOrderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool InsertOrderResult;
        
        public InsertOrderResponse() {
        }
        
        public InsertOrderResponse(bool InsertOrderResult) {
            this.InsertOrderResult = InsertOrderResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/AnderssonLink")]
    public partial class InsertOrderMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int articleNoField;
        
        private bool articleNoFieldSpecified;
        
        private string currencyField;
        
        private string customerField;
        
        private int customerNoField;
        
        private bool customerNoFieldSpecified;
        
        private int customerOrderNoField;
        
        private bool customerOrderNoFieldSpecified;
        
        private System.DateTime deliveryDateField;
        
        private bool deliveryDateFieldSpecified;
        
        private string descriptionField;
        
        private string infoField;
        
        private System.DateTime orderDateField;
        
        private bool orderDateFieldSpecified;
        
        private int piecePriceField;
        
        private bool piecePriceFieldSpecified;
        
        private int quantityField;
        
        private bool quantityFieldSpecified;
        
        private string recipientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int articleNo {
            get {
                return this.articleNoField;
            }
            set {
                this.articleNoField = value;
                this.RaisePropertyChanged("articleNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool articleNoSpecified {
            get {
                return this.articleNoFieldSpecified;
            }
            set {
                this.articleNoFieldSpecified = value;
                this.RaisePropertyChanged("articleNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int customerNo {
            get {
                return this.customerNoField;
            }
            set {
                this.customerNoField = value;
                this.RaisePropertyChanged("customerNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool customerNoSpecified {
            get {
                return this.customerNoFieldSpecified;
            }
            set {
                this.customerNoFieldSpecified = value;
                this.RaisePropertyChanged("customerNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int customerOrderNo {
            get {
                return this.customerOrderNoField;
            }
            set {
                this.customerOrderNoField = value;
                this.RaisePropertyChanged("customerOrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool customerOrderNoSpecified {
            get {
                return this.customerOrderNoFieldSpecified;
            }
            set {
                this.customerOrderNoFieldSpecified = value;
                this.RaisePropertyChanged("customerOrderNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime deliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
                this.RaisePropertyChanged("deliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveryDateSpecified {
            get {
                return this.deliveryDateFieldSpecified;
            }
            set {
                this.deliveryDateFieldSpecified = value;
                this.RaisePropertyChanged("deliveryDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime orderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
                this.RaisePropertyChanged("orderDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderDateSpecified {
            get {
                return this.orderDateFieldSpecified;
            }
            set {
                this.orderDateFieldSpecified = value;
                this.RaisePropertyChanged("orderDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int piecePrice {
            get {
                return this.piecePriceField;
            }
            set {
                this.piecePriceField = value;
                this.RaisePropertyChanged("piecePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool piecePriceSpecified {
            get {
                return this.piecePriceFieldSpecified;
            }
            set {
                this.piecePriceFieldSpecified = value;
                this.RaisePropertyChanged("piecePriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("quantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertOrderByObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertOrderByObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderMessage message;
        
        public InsertOrderByObjectRequest() {
        }
        
        public InsertOrderByObjectRequest(AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderMessage message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertOrderByObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertOrderByObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool InsertOrderByObjectResult;
        
        public InsertOrderByObjectResponse() {
        }
        
        public InsertOrderByObjectResponse(bool InsertOrderByObjectResult) {
            this.InsertOrderByObjectResult = InsertOrderByObjectResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IOrderServiceChannel : AnderssonLinkWCFCallingProject.OrderServiceReference.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<AnderssonLinkWCFCallingProject.OrderServiceReference.IOrderService>, AnderssonLinkWCFCallingProject.OrderServiceReference.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AnderssonLinkWCFCallingProject.OrderServiceReference.GetOrdersResponse AnderssonLinkWCFCallingProject.OrderServiceReference.IOrderService.GetOrders(AnderssonLinkWCFCallingProject.OrderServiceReference.GetOrdersRequest request) {
            return base.Channel.GetOrders(request);
        }
        
        public System.Data.DataSet GetOrders() {
            AnderssonLinkWCFCallingProject.OrderServiceReference.GetOrdersRequest inValue = new AnderssonLinkWCFCallingProject.OrderServiceReference.GetOrdersRequest();
            AnderssonLinkWCFCallingProject.OrderServiceReference.GetOrdersResponse retVal = ((AnderssonLinkWCFCallingProject.OrderServiceReference.IOrderService)(this)).GetOrders(inValue);
            return retVal.GetOrdersResult;
        }
        
        public bool DeleteOrder(int orderId) {
            return base.Channel.DeleteOrder(orderId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderResponse AnderssonLinkWCFCallingProject.OrderServiceReference.IOrderService.InsertOrder(AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderRequest request) {
            return base.Channel.InsertOrder(request);
        }
        
        public bool InsertOrder(int articleNo, string description, System.DateTime orderDate, System.DateTime deliveryDate, int quantity, int piecePrice, string customer, int customerNo, int customerOrderNo, string info, string currency, string recipient) {
            AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderRequest inValue = new AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderRequest();
            inValue.articleNo = articleNo;
            inValue.description = description;
            inValue.orderDate = orderDate;
            inValue.deliveryDate = deliveryDate;
            inValue.quantity = quantity;
            inValue.piecePrice = piecePrice;
            inValue.customer = customer;
            inValue.customerNo = customerNo;
            inValue.customerOrderNo = customerOrderNo;
            inValue.info = info;
            inValue.currency = currency;
            inValue.recipient = recipient;
            AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderResponse retVal = ((AnderssonLinkWCFCallingProject.OrderServiceReference.IOrderService)(this)).InsertOrder(inValue);
            return retVal.InsertOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderByObjectResponse AnderssonLinkWCFCallingProject.OrderServiceReference.IOrderService.InsertOrderByObject(AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderByObjectRequest request) {
            return base.Channel.InsertOrderByObject(request);
        }
        
        public bool InsertOrderByObject(AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderMessage message) {
            AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderByObjectRequest inValue = new AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderByObjectRequest();
            inValue.message = message;
            AnderssonLinkWCFCallingProject.OrderServiceReference.InsertOrderByObjectResponse retVal = ((AnderssonLinkWCFCallingProject.OrderServiceReference.IOrderService)(this)).InsertOrderByObject(inValue);
            return retVal.InsertOrderByObjectResult;
        }
    }
}
